### ISSUE TITLE
Figure out why typecheck fails locally

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/data-modeling#2]
It's pretty mysterious. Locally when I try to run `npm run typecheck` I get:

```
/Users/kentcdodds/code/epicweb-dev/data-modeling/node_modules/typescript/lib/tsc.js:118516
    return filePathsSetList[fileIdsListId - 1];
                           ^

TypeError: Cannot read properties of undefined (reading '0')
    at toFilePathsSet (/Users/kentcdodds/code/epicweb-dev/data-modeling/node_modules/typescript/lib/tsc.js:118516:28)
    at /Users/kentcdodds/code/epicweb-dev/data-modeling/node_modules/typescript/lib/tsc.js:118524:64
    at Array.forEach (<anonymous>)
    at toManyToManyPathMap (/Users/kentcdodds/code/epicweb-dev/data-modeling/node_modules/typescript/lib/tsc.js:118523:18)
    at createBuilderProgramUsingProgramBuildInfo (/Users/kentcdodds/code/epicweb-dev/data-modeling/node_modules/typescript/lib/tsc.js:118471:22)
    at readBuilderProgram (/Users/kentcdodds/code/epicweb-dev/data-modeling/node_modules/typescript/lib/tsc.js:120230:10)
    at getOldProgram (/Users/kentcdodds/code/epicweb-dev/data-modeling/node_modules/typescript/lib/tsc.js:121907:10)
    at createProgram2 (/Users/kentcdodds/code/epicweb-dev/data-modeling/node_modules/typescript/lib/tsc.js:121508:7)
    at executeSteps (/Users/kentcdodds/code/epicweb-dev/data-modeling/node_modules/typescript/lib/tsc.js:121746:11)
    at Object.done (/Users/kentcdodds/code/epicweb-dev/data-modeling/node_modules/typescript/lib/tsc.js:121469:5)

Node.js v18.13.0
NPM command npm run typecheck -- failed with code 1
```

No idea what's going on with this. I've tried re-installing everything 🤷‍♂️

**Comment by kentcdodds** [comment]
This is working fine now.
