### ISSUE TITLE
Undesired behaviors while running the data-modeling workshop

### ISSUE THREAD

**Issue by julianobrasil** [epicweb-dev/data-modeling#53]
After pulling the latest updates I started experiencing 2 undesired behaviors  while running the workshop app:
1.  there's an error thrown to the terminal where the app is running
2. the video audio disappears, I mean... I can watch the video, but it's muted (not sure if this is related, but it wasn't happening before - and it happens randomly)

```bash
aaaaaaaaaaaaaaaaa Error: Unexpected response from partykit: 500 
    at Object.getFreshValue (file:///PATH_FROM_ROOT/data-modeling/epicshop/node_modules/@epic-web/workshop-presence/src/presence.server.ts:49:12)
    at getFreshValue (file:///PATH_FROM_ROOT/data-modeling/epicshop/node_modules/@epic-web/cachified/src/getFreshValue.ts:17:24)
    at cachified (file:///PATH_FROM_ROOT/data-modeling/epicshop/node_modules/@epic-web/cachified/src/cachified.ts:89:17)
    at file:///PATH_FROM_ROOT/data-modeling/epicshop/node_modules/@epic-web/cachified/src/getCachedValue.ts:60:11
```

**Comment by kentcdodds** [comment]
This has been fixed. Sorry about that!
